language: ruby
rvm:
  - 2.6.3

before_script:
 - chmod +x ./script/cibuild # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
# script: ./script/cibuild

script:
- bundle exec jekyll build
# - bundle exec htmlproofer ./_site --disable-external

after_success:
- datetimestamp=$(date --rfc-3339=seconds | sed 's/ /T/'| sed -e "s/:/./g"
)
- git checkout -b travis_build_$datetimestamp
- git add . 
- git commit -m "latest jekyll build from travis $datetimestamp"
- git push -f "https://${GITHUB_TOKEN}@github.com/BlockchainInstituteChi/weteachblockchainsite" travis_build_$datetimestamp

# branch whitelist, only for GitHub Pages
# branches:
#   only:
#   - gh-pages     # test the gh-pages branch
#   - /pages-(.*)/ # test every branch which starts with "pages-"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: gh-pages-test