
collections_dir: all_collections

future: true

keep_files: ['node_modules/']
unpublished: true

collections:
  # permalink: /:name
  authors:
    layout: author
    output: true

  posts:
    layout: post
    output: true

  events: 
    layout: event
    output: true  

  courses:
    output: true

  modules:
    output: false
    
  lessons:
    output: true

  team:
    output: false

  board:
    output: false

  pressReleases:
    output: false    

  faq:
    output: true       
    
  blog: 
    layout: blog
    output: true

sass:
    style: compressed
    load_paths:
        - _sass
        - node_modules

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude :
 - node_modules/      
      
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

include: ["node_modules"]
exclude: []