collections_dir: _collections/

future: true

collections:
  events: 
    layout: event
    output: true  

  courses:
    output: true

  modules:
    output: false
    
  lessons:
    output: true

  team:
    output: false

  board:
    output: false

  pressReleases:
    output: false    

  faq:
    output: true       
    
  blog: 
    layout: blog
    output: true
        
  factoid: 
    output: false

sass:
    style: compressed
    load_paths:
        - _sass
        - node_modules

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude :
 - node_modules/      
      
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

include: ["node_modules"]
exclude: []