#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build

git checkout -b travis_build
git add . 
git commit -m "latest jekyll build from travis $(date --rfc-3339=date)"
git push --set-upstream origin travis_build
# bundle exec htmlproofer ./_site --disable-external